CREATE TABLE IF NOT EXISTS `android` (
  `REPORT_ID` varchar(50) NOT NULL,
  `APP_VERSION` float DEFAULT NULL,
  `APP_VERSION_NAME` varchar(50) DEFAULT NULL,
  `ANDROID_VERSION` varchar(10) DEFAULT NULL,
  `PHONE_MODEL` varchar(255) DEFAULT NULL,
  `PHONE_BRAND` varchar(255) DEFAULT NULL,
  `PRODUCT` varchar(45) DEFAULT NULL,
  `USER_CRASH_DATE` timestamp NULL DEFAULT NULL,
  `PACKAGE_NAME` varchar(255) DEFAULT NULL,
  `STACK_TRACE` text,
  PRIMARY KEY (`REPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;